# -*- coding: utf-8 -*-
"""Adv Lab 1 Lab 2 Temperature

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3yNJY11RopciyMJ9QXX61DZjaWo3QQT
"""

import numpy as np
import matplotlib.pyplot as plt

path = "/content/0,656.csv"
data = np.genfromtxt(path, delimiter=',', names=['times','R'])

time = data['times']*0.001
temp = ((3.354016E-03) + (2.569850E-04)*np.log(data['R']/1000) + (2.620131E-06)*(np.log(data['R']/1000))**2 + (6.383091E-08)*(np.log(data['R']/1000))**3)**(-1)

fig, ax = plt.subplots()

ax.scatter(time, temp, s=4, color='blue')
ax.set_xlabel('Time (s)')
ax.set_ylabel('Temperature (K)')
ax.set_title('Temperature as a function of time')
ax.grid()

plt.show()